package com.arthvritt.platform.document;

import com.arthvritt.platform.audit.Actor;
import com.arthvritt.platform.audit.AuditEnvelopes;
import com.arthvritt.platform.audit.AuditLog;
import com.arthvritt.platform.shared.Ids;
import com.arthvritt.platform.shared.error.NotFoundException;
import com.arthvritt.platform.shared.error.ValidationException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.OffsetDateTime;
import java.util.HexFormat;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * BC16 Documents — {@link DocumentPort} implementation (M18a store core, DL-BE-075).
 *
 * <p>{@link #storeGenerated} is the one-shot path for server-generated bytes (the M18d Form-16A render
 * path): it mints a fresh {@code document_id}, content-addresses the bytes ({@code doc_hash = SHA-256}),
 * inserts the {@code sys_document} handle already {@code status='stored'}, writes the bytes via the
 * swappable {@link DocumentStorePort}, and audits one {@code documents.Document.Stored} envelope carrying
 * ids/hash only — never the raw bytes (DO.2). {@code resolve}/{@code retrieve} are plain reads; the latter
 * throws {@link NotFoundException} for an unknown/not-yet-stored document rather than a 500 (STORE-1 —
 * this port performs no authorization of its own).
 */
@Service
public class DocumentService implements DocumentPort {

    static final String CONTEXT = "documents";

    /**
     * The reserved, non-interactive SYSTEM principal seeded in V7 (DL-BE-064) — reused here as the audit
     * actor and {@code created_by} for server-generated documents, which have no human initiator.
     */
    private static final UUID SYSTEM_ACTOR_ID = UUID.fromString("00000000-0000-0000-0000-000000000002");

    private final JdbcTemplate jdbc;
    private final DocumentStorePort store;
    private final AuditLog auditLog;
    private final long maxUploadBytes;

    public DocumentService(JdbcTemplate jdbc, DocumentStorePort store, AuditLog auditLog,
                           @Value("${documents.max-upload-bytes:20971520}") long maxUploadBytes) {
        this.jdbc = jdbc;
        this.store = store;
        this.auditLog = auditLog;
        this.maxUploadBytes = maxUploadBytes;
    }

    @Override
    @Transactional
    public DocMeta storeGenerated(byte[] rawBytes, String kind, String contentType, String ownerContext, String ownerRef) {
        UUID documentId = Ids.newId();
        byte[] hash = sha256(rawBytes);
        long byteSize = rawBytes.length;
        OffsetDateTime storedAt = OffsetDateTime.now();

        jdbc.update("INSERT INTO sys_document (document_id, kind, owner_context, owner_ref, content_type, "
                        + "status, byte_size, doc_hash, created_by, stored_at) "
                        + "VALUES (?, ?, ?, ?, ?, 'stored'::sys_document_status, ?, ?, ?, ?)",
                documentId, kind, ownerContext, ownerRef, contentType, byteSize, hash, SYSTEM_ACTOR_ID, storedAt);

        store.put(documentId, rawBytes);

        auditLog.append(AuditEnvelopes.seed(CONTEXT, "Document", documentId)
                .eventType(CONTEXT + ".Document.Stored")
                .actor(new Actor("system", SYSTEM_ACTOR_ID.toString(), null, null, null))
                .payload(Map.of(
                        "document_id", documentId.toString(),
                        "kind", kind,
                        "doc_hash", HexFormat.of().formatHex(hash),
                        "byte_size", byteSize))
                .build());

        return new DocMeta(documentId, kind, "stored", contentType, byteSize, hash);
    }

    @Override
    public Optional<DocMeta> resolve(UUID documentId) {
        DocMeta meta = jdbc.query("SELECT document_id, kind, status::text AS status, content_type, "
                        + "byte_size, doc_hash FROM sys_document WHERE document_id = ?",
                rs -> rs.next() ? new DocMeta(
                        rs.getObject("document_id", UUID.class),
                        rs.getString("kind"),
                        rs.getString("status"),
                        rs.getString("content_type"),
                        rs.getObject("byte_size") == null ? 0L : rs.getLong("byte_size"),
                        rs.getBytes("doc_hash"))
                        : null,
                documentId);
        return Optional.ofNullable(meta);
    }

    @Override
    public byte[] retrieve(UUID documentId) {
        DocMeta meta = resolve(documentId)
                .orElseThrow(() -> new NotFoundException("document not found: " + documentId));
        if (!"stored".equals(meta.status())) {
            throw new NotFoundException("document not yet stored: " + documentId);
        }
        return store.get(documentId);
    }

    @Override
    @Transactional
    public UploadTicket initiate(UUID documentId, String kind, String contentType, long declaredSize, UUID createdBy) {
        // Idempotent on document_id (the caller derives it deterministically from X-Command-Id): a replay
        // is a no-op INSERT (0 rows) — no second row, no second audit envelope.
        int inserted = jdbc.update("INSERT INTO sys_document (document_id, kind, content_type, created_by) "
                        + "VALUES (?, ?, ?, ?) ON CONFLICT (document_id) DO NOTHING",
                documentId, kind, contentType, createdBy);
        if (inserted == 1) {
            auditLog.append(AuditEnvelopes.seed(CONTEXT, "Document", documentId)
                    .eventType(CONTEXT + ".Document.Initiated")
                    .actor(new Actor("admin_user", createdBy.toString(), null, null, null))
                    .payload(Map.of("document_id", documentId.toString(), "kind", kind,
                            "declared_size", declaredSize))
                    .build());
        }
        return new UploadTicket(documentId, "/documents/" + documentId + "/content");
    }

    @Override
    @Transactional
    public void uploadContent(UUID documentId, byte[] bytes) {
        if (resolve(documentId).isEmpty()) {
            throw new NotFoundException("document not found: " + documentId);
        }
        // I4: validate BEFORE any bytes are persisted — a rejected upload must leave no sys_document_blob row.
        if (bytes.length > maxUploadBytes) {
            throw new ValidationException(
                    "upload exceeds the " + maxUploadBytes + "-byte cap: " + bytes.length + " bytes");
        }
        store.put(documentId, bytes);
    }

    @Override
    @Transactional
    public DocMeta finalizeUpload(UUID documentId, UUID actorId) {
        DocMeta current = resolve(documentId)
                .orElseThrow(() -> new NotFoundException("document not found: " + documentId));
        if ("stored".equals(current.status())) {
            return current; // idempotent replay: no-op, no second audit envelope
        }
        if (!store.exists(documentId)) {
            throw new ValidationException("no content uploaded for document " + documentId + " — PUT the "
                    + "content before finalizing");
        }
        byte[] bytes = store.get(documentId);
        byte[] hash = sha256(bytes);
        long byteSize = bytes.length;
        OffsetDateTime storedAt = OffsetDateTime.now();

        // Status-guarded UPDATE (the WS-6/WS-7 rowcount lesson) — a concurrent finalize would make this a
        // no-op here too; the STATUS-1 CHECK backstops either way.
        int updated = jdbc.update("UPDATE sys_document SET status = 'stored'::sys_document_status, "
                        + "byte_size = ?, doc_hash = ?, stored_at = ? "
                        + "WHERE document_id = ? AND status = 'pending_upload'::sys_document_status",
                byteSize, hash, storedAt, documentId);
        if (updated != 1) {
            // Lost a race with a concurrent finalize; the other caller's row is the one that stuck.
            return resolve(documentId).orElseThrow(() -> new NotFoundException("document not found: " + documentId));
        }

        auditLog.append(AuditEnvelopes.seed(CONTEXT, "Document", documentId)
                .eventType(CONTEXT + ".Document.Stored")
                .actor(new Actor("admin_user", actorId.toString(), null, null, null))
                .payload(Map.of(
                        "document_id", documentId.toString(),
                        "kind", current.kind(),
                        "doc_hash", HexFormat.of().formatHex(hash),
                        "byte_size", byteSize))
                .build());

        return new DocMeta(documentId, current.kind(), "stored", current.contentType(), byteSize, hash);
    }

    private static byte[] sha256(byte[] input) {
        try {
            return MessageDigest.getInstance("SHA-256").digest(input);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 unavailable", e);
        }
    }
}
